version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: tail -f /dev/null
